mysql:
  image: yobasystems/alpine-mariadb
  env_file: .env

cacti:
  image: vault/cacti
  ports: 
    - "80:80"
  links:
    - "mysql:mysql"
  env_file: .env
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
